
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryManagement?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1999
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: false
#    properties:
#      hibernate:
#        session_factory:
#          interceptor: com.rafaa.inventoryManagement.interceptor.Interceptor

    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081